services:
  chinook-db:
    image: postgres:16-alpine
    container_name: blog-db
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
    - ./postgres/init-db:/docker-entrypoint-initdb.d
    - ./blog_data:/var/lib/postgresql/data
